-- Highlight groups for GrokNight / GrokDay
-- Spirit (from Herdr/Ghostty captures): near-black chrome, muted UI,
-- bright color only for accents/syntax. Yellow = focus.

local M = {}

---@param c table palette
---@return table<string, table>
function M.get(c)
  return {
    -- ── Editor ──────────────────────────────────────────────
    Normal = { fg = c.fg, bg = c.bg },
    NormalNC = { fg = c.fg_secondary, bg = c.bg },
    NormalFloat = { fg = c.fg, bg = c.bg_float },
    FloatBorder = { fg = c.bg_highlight, bg = c.bg_float },
    FloatTitle = { fg = c.yellow, bg = c.bg_float, bold = true },
    ColorColumn = { bg = c.surface0 },
    Cursor = { fg = c.bg, bg = c.yellow },
    lCursor = { fg = c.bg, bg = c.yellow },
    CursorIM = { fg = c.bg, bg = c.yellow },
    CursorColumn = { bg = c.bg_highlight },
    CursorLine = { bg = c.bg_highlight },
    CursorLineNr = { fg = c.yellow, bold = true },
    LineNr = { fg = c.fg_gutter },
    LineNrAbove = { fg = c.fg_gutter },
    LineNrBelow = { fg = c.fg_gutter },
    SignColumn = { fg = c.fg_gutter, bg = c.bg },
    SignColumnSB = { fg = c.fg_gutter, bg = c.bg_sidebar },
    Folded = { fg = c.comment, bg = c.surface0 },
    FoldColumn = { fg = c.fg_gutter, bg = c.bg },
    MatchParen = { fg = c.orange, bold = true },
    NonText = { fg = c.fg_gutter },
    EndOfBuffer = { fg = c.bg },
    Whitespace = { fg = c.fg_gutter },
    SpecialKey = { fg = c.fg_gutter },
    Visual = { bg = c.bg_visual },
    VisualNOS = { bg = c.bg_visual },
    Search = { fg = c.bg, bg = c.yellow },
    IncSearch = { fg = c.bg, bg = c.orange },
    CurSearch = { fg = c.bg, bg = c.orange },
    Substitute = { fg = c.bg, bg = c.red },
    WildMenu = { bg = c.bg_visual },
    -- dirs green like Ghostty/Nushell listings
    Directory = { fg = c.green },
    Title = { fg = c.yellow, bold = true },
    ErrorMsg = { fg = c.red },
    WarningMsg = { fg = c.yellow },
    MoreMsg = { fg = c.blue },
    ModeMsg = { fg = c.fg_secondary, bold = true },
    Question = { fg = c.blue },
    MsgArea = { fg = c.fg_secondary },
    QuickFixLine = { bg = c.bg_visual, bold = true },
    Pmenu = { fg = c.fg, bg = c.bg_popup },
    PmenuSel = { bg = c.bg_highlight, fg = c.fg },
    PmenuSbar = { bg = c.bg_popup },
    PmenuThumb = { bg = c.bg_highlight },
    PmenuKind = { fg = c.blue, bg = c.bg_popup },
    PmenuExtra = { fg = c.comment, bg = c.bg_popup },
    StatusLine = { fg = c.fg_secondary, bg = c.bg_statusline },
    StatusLineNC = { fg = c.comment, bg = c.bg_statusline },
    -- Tabs: inactive muted void; active soft + yellow accent elsewhere
    TabLine = { fg = c.comment, bg = c.bg_dark },
    TabLineFill = { bg = c.bg_terminal },
    TabLineSel = { fg = c.fg, bg = c.bg, bold = true },
    WinBar = { fg = c.fg_secondary, bg = c.bg },
    WinBarNC = { fg = c.comment, bg = c.bg },
    WinSeparator = { fg = c.bg_highlight },
    VertSplit = { fg = c.bg_highlight },
    Conceal = { fg = c.comment },
    SpellBad = { sp = c.red, undercurl = true },
    SpellCap = { sp = c.yellow, undercurl = true },
    SpellLocal = { sp = c.blue, undercurl = true },
    SpellRare = { sp = c.purple, undercurl = true },
    DiffAdd = { bg = c.diff_add },
    DiffChange = { bg = c.diff_change },
    DiffDelete = { bg = c.diff_delete },
    DiffText = { bg = c.diff_text },
    diffAdded = { fg = c.git_add },
    diffRemoved = { fg = c.git_delete },
    diffChanged = { fg = c.git_change },
    diffFile = { fg = c.blue },
    diffIndexLine = { fg = c.magenta },
    diffLine = { fg = c.comment },

    -- ── Syntax (legacy) ─────────────────────────────────────
    Comment = { fg = c.comment, italic = true },
    Constant = { fg = c.orange },
    String = { fg = c.green },
    Character = { fg = c.green },
    Number = { fg = c.orange },
    Boolean = { fg = c.orange },
    Float = { fg = c.orange },
    Identifier = { fg = c.magenta },
    Function = { fg = c.blue },
    Statement = { fg = c.purple },
    Conditional = { fg = c.purple },
    Repeat = { fg = c.purple },
    Label = { fg = c.blue },
    Operator = { fg = c.cyan },
    Keyword = { fg = c.purple },
    Exception = { fg = c.purple },
    PreProc = { fg = c.cyan },
    Include = { fg = c.purple },
    Define = { fg = c.purple },
    Macro = { fg = c.cyan },
    PreCondit = { fg = c.cyan },
    Type = { fg = c.cyan },
    StorageClass = { fg = c.cyan },
    Structure = { fg = c.yellow },
    Typedef = { fg = c.yellow },
    Special = { fg = c.blue },
    SpecialChar = { fg = c.orange },
    Tag = { fg = c.red },
    Delimiter = { fg = c.fg_secondary },
    SpecialComment = { fg = c.comment },
    Debug = { fg = c.orange },
    Underlined = { underline = true },
    Bold = { bold = true },
    Italic = { italic = true },
    Error = { fg = c.red },
    Todo = { fg = c.bg, bg = c.yellow, bold = true },

    -- ── Treesitter ──────────────────────────────────────────
    ["@comment"] = { link = "Comment" },
    ["@comment.documentation"] = { fg = c.comment, italic = true },
    ["@comment.error"] = { fg = c.red },
    ["@comment.warning"] = { fg = c.yellow },
    ["@comment.todo"] = { fg = c.bg, bg = c.yellow, bold = true },
    ["@comment.note"] = { fg = c.bg, bg = c.blue, bold = true },

    ["@constant"] = { fg = c.orange },
    ["@constant.builtin"] = { fg = c.orange },
    ["@constant.macro"] = { fg = c.cyan },
    ["@boolean"] = { fg = c.orange },
    ["@number"] = { fg = c.orange },
    ["@number.float"] = { fg = c.orange },
    ["@string"] = { fg = c.green },
    ["@string.documentation"] = { fg = c.green },
    ["@string.regexp"] = { fg = c.cyan },
    ["@string.escape"] = { fg = c.magenta },
    ["@string.special"] = { fg = c.yellow },
    ["@string.special.symbol"] = { fg = c.orange },
    ["@string.special.path"] = { fg = c.yellow },
    ["@string.special.url"] = { fg = c.link, underline = true },
    ["@character"] = { fg = c.green },
    ["@character.special"] = { fg = c.orange },

    ["@variable"] = { fg = c.fg },
    ["@variable.builtin"] = { fg = c.red },
    ["@variable.parameter"] = { fg = c.yellow },
    ["@variable.parameter.builtin"] = { fg = c.yellow },
    ["@variable.member"] = { fg = c.green1 },

    ["@property"] = { fg = c.green1 },
    ["@attribute"] = { fg = c.cyan },
    ["@attribute.builtin"] = { fg = c.cyan },
    ["@module"] = { fg = c.cyan },
    ["@module.builtin"] = { fg = c.cyan },
    ["@label"] = { fg = c.blue },

    ["@type"] = { fg = c.cyan },
    ["@type.builtin"] = { fg = c.cyan },
    ["@type.definition"] = { fg = c.cyan },
    ["@type.qualifier"] = { fg = c.purple },

    ["@function"] = { fg = c.blue },
    ["@function.builtin"] = { fg = c.blue },
    ["@function.call"] = { fg = c.blue },
    ["@function.macro"] = { fg = c.cyan },
    ["@function.method"] = { fg = c.blue },
    ["@function.method.call"] = { fg = c.blue },
    ["@constructor"] = { fg = c.magenta },
    ["@operator"] = { fg = c.cyan },

    ["@keyword"] = { fg = c.purple },
    ["@keyword.function"] = { fg = c.purple },
    ["@keyword.operator"] = { fg = c.purple },
    ["@keyword.import"] = { fg = c.purple },
    ["@keyword.type"] = { fg = c.purple },
    ["@keyword.modifier"] = { fg = c.purple },
    ["@keyword.repeat"] = { fg = c.purple },
    ["@keyword.return"] = { fg = c.purple },
    ["@keyword.debug"] = { fg = c.orange },
    ["@keyword.exception"] = { fg = c.purple },
    ["@keyword.conditional"] = { fg = c.purple },
    ["@keyword.conditional.ternary"] = { fg = c.purple },
    ["@keyword.directive"] = { fg = c.cyan },
    ["@keyword.directive.define"] = { fg = c.cyan },
    ["@keyword.coroutine"] = { fg = c.purple },

    ["@punctuation.delimiter"] = { fg = c.fg_secondary },
    ["@punctuation.bracket"] = { fg = c.fg_secondary },
    ["@punctuation.special"] = { fg = c.cyan },

    ["@tag"] = { fg = c.red },
    ["@tag.attribute"] = { fg = c.orange },
    ["@tag.delimiter"] = { fg = c.dark5 },

    ["@markup.heading"] = { fg = c.blue, bold = true },
    ["@markup.heading.1"] = { fg = c.blue, bold = true },
    ["@markup.heading.2"] = { fg = c.yellow, bold = true },
    ["@markup.heading.3"] = { fg = c.green, bold = true },
    ["@markup.heading.4"] = { fg = c.teal, bold = true },
    ["@markup.heading.5"] = { fg = c.magenta, bold = true },
    ["@markup.heading.6"] = { fg = c.purple, bold = true },
    ["@markup.strong"] = { bold = true },
    ["@markup.italic"] = { italic = true },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.underline"] = { underline = true },
    ["@markup.quote"] = { fg = c.fg_secondary, italic = true },
    ["@markup.math"] = { fg = c.blue },
    ["@markup.link"] = { fg = c.teal },
    ["@markup.link.label"] = { fg = c.teal },
    ["@markup.link.url"] = { fg = c.link, underline = true },
    ["@markup.raw"] = { fg = c.green },
    ["@markup.raw.block"] = { fg = c.green },
    ["@markup.list"] = { fg = c.cyan },
    ["@markup.list.checked"] = { fg = c.green },
    ["@markup.list.unchecked"] = { fg = c.comment },

    ["@diff.plus"] = { fg = c.git_add },
    ["@diff.minus"] = { fg = c.git_delete },
    ["@diff.delta"] = { fg = c.git_change },

    -- ── LSP semantic tokens ─────────────────────────────────
    ["@lsp.type.class"] = { link = "@type" },
    ["@lsp.type.comment"] = { link = "@comment" },
    ["@lsp.type.decorator"] = { link = "@attribute" },
    ["@lsp.type.enum"] = { link = "@type" },
    ["@lsp.type.enumMember"] = { link = "@constant" },
    ["@lsp.type.function"] = { link = "@function" },
    ["@lsp.type.interface"] = { link = "@type" },
    ["@lsp.type.macro"] = { link = "@function.macro" },
    ["@lsp.type.method"] = { link = "@function.method" },
    ["@lsp.type.namespace"] = { link = "@module" },
    ["@lsp.type.parameter"] = { link = "@variable.parameter" },
    ["@lsp.type.property"] = { link = "@property" },
    ["@lsp.type.struct"] = { link = "@type" },
    ["@lsp.type.type"] = { link = "@type" },
    ["@lsp.type.typeParameter"] = { link = "@type.definition" },
    ["@lsp.type.variable"] = { link = "@variable" },
    ["@lsp.typemod.function.defaultLibrary"] = { link = "@function.builtin" },
    ["@lsp.typemod.variable.defaultLibrary"] = { link = "@variable.builtin" },
    ["@lsp.typemod.variable.injected"] = { link = "@variable" },
    ["@lsp.mod.deprecated"] = { strikethrough = true },

    -- ── Diagnostics ─────────────────────────────────────────
    DiagnosticError = { fg = c.red },
    DiagnosticWarn = { fg = c.yellow },
    DiagnosticInfo = { fg = c.blue },
    DiagnosticHint = { fg = c.teal },
    DiagnosticOk = { fg = c.green },
    DiagnosticUnderlineError = { sp = c.red, undercurl = true },
    DiagnosticUnderlineWarn = { sp = c.yellow, undercurl = true },
    DiagnosticUnderlineInfo = { sp = c.blue, undercurl = true },
    DiagnosticUnderlineHint = { sp = c.teal, undercurl = true },
    DiagnosticUnderlineOk = { sp = c.green, undercurl = true },
    DiagnosticVirtualTextError = { fg = c.red, bg = c.diff_delete },
    DiagnosticVirtualTextWarn = { fg = c.yellow, bg = c.diff_change },
    DiagnosticVirtualTextInfo = { fg = c.blue },
    DiagnosticVirtualTextHint = { fg = c.teal },
    DiagnosticVirtualTextOk = { fg = c.green },
    DiagnosticFloatingError = { link = "DiagnosticError" },
    DiagnosticFloatingWarn = { link = "DiagnosticWarn" },
    DiagnosticFloatingInfo = { link = "DiagnosticInfo" },
    DiagnosticFloatingHint = { link = "DiagnosticHint" },
    DiagnosticSignError = { link = "DiagnosticError" },
    DiagnosticSignWarn = { link = "DiagnosticWarn" },
    DiagnosticSignInfo = { link = "DiagnosticInfo" },
    DiagnosticSignHint = { link = "DiagnosticHint" },
    LspReferenceText = { bg = c.bg_highlight },
    LspReferenceRead = { bg = c.bg_highlight },
    LspReferenceWrite = { bg = c.bg_highlight },
    LspSignatureActiveParameter = { bg = c.bg_visual, bold = true },
    LspCodeLens = { fg = c.comment },
    LspInlayHint = { fg = c.dark3, bg = c.bg_highlight },
    LspInfoBorder = { link = "FloatBorder" },

    -- ── GitSigns ────────────────────────────────────────────
    GitSignsAdd = { fg = c.git_add },
    GitSignsChange = { fg = c.git_change },
    GitSignsDelete = { fg = c.git_delete },
    GitSignsAddNr = { fg = c.git_add },
    GitSignsChangeNr = { fg = c.git_change },
    GitSignsDeleteNr = { fg = c.git_delete },
    GitSignsCurrentLineBlame = { fg = c.comment, italic = true },

    -- ── Telescope ───────────────────────────────────────────
    TelescopeNormal = { fg = c.fg, bg = c.bg_float },
    TelescopeBorder = { fg = c.bg_highlight, bg = c.bg_float },
    TelescopeTitle = { fg = c.yellow, bold = true },
    TelescopePromptNormal = { fg = c.fg, bg = c.bg_float },
    TelescopePromptBorder = { fg = c.bg_highlight, bg = c.bg_float },
    TelescopePromptTitle = { fg = c.yellow, bold = true },
    TelescopePromptPrefix = { fg = c.yellow },
    TelescopeSelection = { fg = c.fg, bg = c.bg_highlight },
    TelescopeSelectionCaret = { fg = c.yellow },
    TelescopeMatching = { fg = c.orange, bold = true },
    TelescopeResultsComment = { fg = c.comment },
    TelescopeResultsNormal = { fg = c.fg },
    TelescopeResultsTitle = { fg = c.yellow, bold = true },
    TelescopeResultsBorder = { fg = c.bg_highlight, bg = c.bg_float },
    TelescopePreviewTitle = { fg = c.green, bold = true },
    TelescopeMultiSelection = { fg = c.magenta },

    -- ── Fzf-Lua ─────────────────────────────────────────────
    FzfLuaNormal = { fg = c.fg, bg = c.bg_float },
    FzfLuaBorder = { fg = c.bg_highlight, bg = c.bg_float },
    FzfLuaTitle = { fg = c.yellow, bold = true },
    FzfLuaCursor = { fg = c.bg, bg = c.yellow },
    FzfLuaCursorLine = { fg = c.fg, bg = c.bg_highlight },
    FzfLuaSearch = { fg = c.orange, bold = true },
    FzfLuaDir = { fg = c.green },
    FzfLuaPath = { fg = c.fg },
    FzfLuaPathLineNr = { fg = c.comment },

    -- ── nvim-cmp / blink.cmp ────────────────────────────────
    CmpItemAbbr = { fg = c.fg },
    CmpItemAbbrDeprecated = { fg = c.comment, strikethrough = true },
    CmpItemAbbrMatch = { fg = c.orange, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = c.orange },
    CmpItemKind = { fg = c.blue },
    CmpItemMenu = { fg = c.comment },
    CmpItemKindClass = { fg = c.yellow },
    CmpItemKindColor = { fg = c.red },
    CmpItemKindConstant = { fg = c.orange },
    CmpItemKindConstructor = { fg = c.blue },
    CmpItemKindEnum = { fg = c.yellow },
    CmpItemKindEnumMember = { fg = c.green1 },
    CmpItemKindEvent = { fg = c.yellow },
    CmpItemKindField = { fg = c.green1 },
    CmpItemKindFile = { fg = c.blue },
    CmpItemKindFolder = { fg = c.blue },
    CmpItemKindFunction = { fg = c.blue },
    CmpItemKindInterface = { fg = c.yellow },
    CmpItemKindKeyword = { fg = c.purple },
    CmpItemKindMethod = { fg = c.blue },
    CmpItemKindModule = { fg = c.cyan },
    CmpItemKindOperator = { fg = c.cyan },
    CmpItemKindProperty = { fg = c.green1 },
    CmpItemKindReference = { fg = c.red },
    CmpItemKindSnippet = { fg = c.teal },
    CmpItemKindStruct = { fg = c.yellow },
    CmpItemKindText = { fg = c.fg },
    CmpItemKindTypeParameter = { fg = c.cyan },
    CmpItemKindUnit = { fg = c.orange },
    CmpItemKindValue = { fg = c.orange },
    CmpItemKindVariable = { fg = c.magenta },
    BlinkCmpMenu = { fg = c.fg, bg = c.bg_popup },
    BlinkCmpMenuBorder = { fg = c.bg_highlight, bg = c.bg_popup },
    BlinkCmpMenuSelection = { bg = c.bg_highlight },
    BlinkCmpLabel = { fg = c.fg },
    BlinkCmpLabelMatch = { fg = c.orange, bold = true },
    BlinkCmpLabelDeprecated = { fg = c.comment, strikethrough = true },
    BlinkCmpKind = { fg = c.blue },
    BlinkCmpDoc = { fg = c.fg, bg = c.bg_float },
    BlinkCmpDocBorder = { fg = c.bg_highlight, bg = c.bg_float },
    BlinkCmpSignatureHelp = { fg = c.fg, bg = c.bg_float },
    BlinkCmpSignatureHelpBorder = { fg = c.bg_highlight, bg = c.bg_float },

    -- ── Neo-tree / NvimTree ─────────────────────────────────
    -- Explorer = monochrome void (Herdr sidebar spirit). No rainbow icons.
    NeoTreeNormal = { fg = c.comment, bg = c.bg_sidebar },
    NeoTreeNormalNC = { fg = c.fg_gutter, bg = c.bg_sidebar },
    NeoTreeEndOfBuffer = { fg = c.bg_sidebar },
    -- Selection: lift clearly off void (#0a) — was #242424 (ton sur ton)
    NeoTreeCursorLine = { bg = c.surface2, fg = c.fg },
    NeoTreeDirectoryName = { fg = c.fg_secondary },
    NeoTreeDirectoryIcon = { fg = c.fg_gutter },
    NeoTreeFileName = { fg = c.comment },
    NeoTreeFileIcon = { fg = c.fg_gutter },
    NeoTreeFileNameOpened = { fg = c.fg_secondary },
    NeoTreeRootName = { fg = c.fg_secondary, bold = true },
    NeoTreeSymbolicLinkTarget = { fg = c.comment },
    NeoTreeDimText = { fg = c.fg_gutter },
    NeoTreeDotfile = { fg = c.fg_gutter },
    NeoTreeHiddenByName = { fg = c.fg_gutter },
    -- Git: barely-there hints, not neon status
    NeoTreeGitAdded = { fg = c.dark5 },
    NeoTreeGitModified = { fg = c.dark5 },
    NeoTreeGitDeleted = { fg = c.dark3 },
    NeoTreeGitConflict = { fg = c.comment },
    NeoTreeGitUntracked = { fg = c.fg_gutter },
    NeoTreeGitIgnored = { fg = c.fg_gutter },
    NeoTreeIndentMarker = { fg = c.fg_gutter },
    NeoTreeExpander = { fg = c.fg_gutter },
    NeoTreeFloatBorder = { link = "FloatBorder" },
    NeoTreeFloatTitle = { fg = c.comment, bg = c.bg_float },
    NeoTreeTitleBar = { fg = c.comment, bg = c.bg_dark },
    NeoTreeTabActive = { fg = c.fg_secondary, bg = c.bg },
    NeoTreeTabInactive = { fg = c.fg_gutter, bg = c.bg_dark },
    NeoTreeTabSeparatorActive = { fg = c.bg, bg = c.bg },
    NeoTreeTabSeparatorInactive = { fg = c.bg_terminal, bg = c.bg_dark },
    NeoTreeWinSeparator = { fg = c.bg_highlight, bg = c.bg_sidebar },
    NeoTreeStats = { fg = c.fg_gutter },
    NeoTreeStatsHeader = { fg = c.fg_gutter },
    NeoTreeFilterTerm = { fg = c.fg_secondary },
    NeoTreeFloatNormal = { fg = c.comment, bg = c.bg_float },
    NvimTreeNormal = { link = "NeoTreeNormal" },
    NvimTreeNormalNC = { link = "NeoTreeNormalNC" },
    NvimTreeFolderName = { link = "NeoTreeDirectoryName" },
    NvimTreeOpenedFolderName = { fg = c.fg_secondary },
    NvimTreeEmptyFolderName = { fg = c.comment },
    NvimTreeFolderIcon = { fg = c.fg_gutter },
    NvimTreeOpenedFolderIcon = { fg = c.fg_gutter },
    NvimTreeClosedFolderIcon = { fg = c.fg_gutter },
    NvimTreeRootFolder = { link = "NeoTreeRootName" },
    NvimTreeIndentMarker = { link = "NeoTreeIndentMarker" },
    NvimTreeGitNew = { link = "NeoTreeGitAdded" },
    NvimTreeGitDirty = { link = "NeoTreeGitModified" },
    NvimTreeGitDeleted = { link = "NeoTreeGitDeleted" },
    NvimTreeGitIgnored = { link = "NeoTreeGitIgnored" },
    NvimTreeGitMerge = { link = "NeoTreeGitConflict" },
    NvimTreeGitRenamed = { fg = c.dark5 },
    NvimTreeGitStaged = { fg = c.dark5 },
    NvimTreeImageFile = { fg = c.comment },
    NvimTreeSpecialFile = { fg = c.comment },
    NvimTreeExecFile = { fg = c.comment },
    NvimTreeSymlink = { fg = c.comment },
    NvimTreeCursorLine = { link = "NeoTreeCursorLine" },
    NvimTreeWinSeparator = { link = "NeoTreeWinSeparator" },
    NvimTreeLiveFilterPrefix = { fg = c.fg_secondary },
    NvimTreeLiveFilterValue = { fg = c.fg },

    -- ── Which-key ───────────────────────────────────────────
    WhichKey = { fg = c.yellow },
    WhichKeyGroup = { fg = c.blue },
    WhichKeyDesc = { fg = c.fg_secondary },
    WhichKeySeperator = { fg = c.fg_gutter },
    WhichKeySeparator = { fg = c.fg_gutter },
    WhichKeyFloat = { bg = c.bg_float },
    WhichKeyBorder = { fg = c.bg_highlight, bg = c.bg_float },
    WhichKeyValue = { fg = c.comment },

    -- ── Indent blankline ────────────────────────────────────
    IblIndent = { fg = c.fg_gutter, nocombine = true },
    IblScope = { fg = c.dark3, nocombine = true },
    IndentBlanklineChar = { link = "IblIndent" },
    IndentBlanklineContextChar = { link = "IblScope" },

    -- ── Lazy ────────────────────────────────────────────────
    LazyNormal = { fg = c.fg, bg = c.bg_float },
    LazyButton = { bg = c.bg_highlight },
    LazyButtonActive = { bg = c.bg_visual, bold = true },
    LazyH1 = { fg = c.bg, bg = c.yellow, bold = true },
    LazyH2 = { fg = c.blue, bold = true },
    LazyProgressDone = { fg = c.green, bold = true },
    LazyProgressTodo = { fg = c.fg_gutter },
    LazySpecial = { fg = c.cyan },
    LazyReasonPlugin = { fg = c.magenta },
    LazyReasonEvent = { fg = c.yellow },
    LazyReasonKeys = { fg = c.teal },
    LazyReasonStart = { fg = c.red },
    LazyReasonSource = { fg = c.blue },
    LazyReasonRuntime = { fg = c.purple },
    LazyReasonCmd = { fg = c.orange },

    -- ── Mason ───────────────────────────────────────────────
    MasonNormal = { fg = c.fg, bg = c.bg_float },
    MasonHeader = { fg = c.bg, bg = c.yellow, bold = true },
    MasonHighlight = { fg = c.blue },
    MasonHighlightBlock = { fg = c.bg, bg = c.blue },
    MasonHighlightBlockBold = { fg = c.bg, bg = c.blue, bold = true },
    MasonMuted = { fg = c.comment },
    MasonMutedBlock = { fg = c.comment, bg = c.bg_highlight },

    -- ── Notify ──────────────────────────────────────────────
    NotifyBackground = { bg = c.bg },
    NotifyERRORBorder = { fg = c.red },
    NotifyWARNBorder = { fg = c.yellow },
    NotifyINFOBorder = { fg = c.blue },
    NotifyDEBUGBorder = { fg = c.comment },
    NotifyTRACEBorder = { fg = c.purple },
    NotifyERRORIcon = { fg = c.red },
    NotifyWARNIcon = { fg = c.yellow },
    NotifyINFOIcon = { fg = c.blue },
    NotifyDEBUGIcon = { fg = c.comment },
    NotifyTRACEIcon = { fg = c.purple },
    NotifyERRORTitle = { fg = c.red },
    NotifyWARNTitle = { fg = c.yellow },
    NotifyINFOTitle = { fg = c.blue },
    NotifyDEBUGTitle = { fg = c.comment },
    NotifyTRACETitle = { fg = c.purple },

    -- ── Noice ───────────────────────────────────────────────
    NoiceCmdlinePopupBorder = { fg = c.yellow },
    NoiceCmdlineIcon = { fg = c.yellow },
    NoiceCompletionItemKindDefault = { fg = c.fg_secondary },
    NoicePopupmenuSelected = { bg = c.bg_highlight },

    -- ── Dashboard / Snacks ──────────────────────────────────
    DashboardHeader = { fg = c.fg_gutter },
    DashboardCenter = { fg = c.fg_secondary },
    DashboardFooter = { fg = c.comment, italic = true },
    DashboardKey = { fg = c.yellow },
    DashboardDesc = { fg = c.comment },
    DashboardIcon = { fg = c.fg_gutter },
    SnacksDashboardHeader = { fg = c.fg_gutter },
    SnacksDashboardDesc = { fg = c.comment },
    SnacksDashboardKey = { fg = c.yellow },
    SnacksDashboardIcon = { fg = c.fg_gutter },
    SnacksDashboardFooter = { fg = c.comment },
    SnacksIndent = { fg = c.fg_gutter },
    SnacksIndentScope = { fg = c.dark3 },
    -- Snacks explorer / picker — monochrome void (no rainbow file tree)
    SnacksPicker = { fg = c.comment, bg = c.bg_float },
    SnacksPickerBorder = { fg = c.bg_highlight, bg = c.bg_float },
    SnacksPickerTitle = { fg = c.fg_secondary },
    SnacksPickerMatch = { fg = c.fg, bold = true },
    SnacksPickerDir = { fg = c.fg_secondary },
    SnacksPickerFile = { fg = c.comment },
    SnacksPickerPathHidden = { fg = c.fg_gutter },
    SnacksPickerPathIgnored = { fg = c.fg_gutter },
    SnacksPickerGitStatus = { fg = c.fg_gutter },
    SnacksPickerGitStatusUntracked = { fg = c.fg_gutter },
    SnacksPickerGitStatusModified = { fg = c.dark5 },
    SnacksPickerGitStatusAdded = { fg = c.dark5 },
    SnacksPickerGitStatusDeleted = { fg = c.dark3 },
    SnacksPickerGitStatusIgnored = { fg = c.fg_gutter },
    SnacksPickerGitStatusUnmerged = { fg = c.comment },
    SnacksPickerGitStatusStaged = { fg = c.dark5 },
    SnacksPickerTree = { fg = c.fg_gutter },
    -- Selection bar: surface2 (#2a2a2a) on sidebar void (#0a0a0a)
    SnacksPickerCursorLine = { bg = c.surface2, fg = c.fg },
    SnacksPickerListCursorLine = { bg = c.surface2, fg = c.fg },
    SnacksPickerPreviewCursorLine = { bg = c.bg_highlight },
    SnacksPickerSelected = { fg = c.fg },
    SnacksPickerIcon = { fg = c.fg_gutter },
    SnacksPickerIconFile = { fg = c.fg_gutter },
    SnacksPickerIconDir = { fg = c.fg_gutter },
    SnacksPickerIconDirOpen = { fg = c.fg_gutter },
    SnacksPickerIconDirectory = { fg = c.fg_gutter },
    SnacksPickerIconDirectoryOpen = { fg = c.fg_gutter },
    SnacksPickerDirectory = { fg = c.fg_secondary },
    SnacksExplorer = { fg = c.comment, bg = c.bg_sidebar },
    SnacksExplorerNormal = { fg = c.comment, bg = c.bg_sidebar },
    SnacksExplorerTitle = { fg = c.fg_secondary },
    SnacksExplorerCursorLine = { bg = c.surface2, fg = c.fg },

    -- ── Bufferline — Herdr-style: dark tabs, yellow on active ─
    BufferLineFill = { bg = c.bg_terminal },
    BufferLineBackground = { fg = c.comment, bg = c.bg_dark },
    BufferLineBuffer = { fg = c.comment, bg = c.bg_dark },
    BufferLineBufferSelected = { fg = c.fg, bg = c.bg, bold = true },
    BufferLineBufferVisible = { fg = c.fg_secondary, bg = c.bg_dark },
    BufferLineIndicatorSelected = { fg = c.yellow, bg = c.bg },
    BufferLineIndicatorVisible = { fg = c.bg_dark, bg = c.bg_dark },
    BufferLineModified = { fg = c.yellow, bg = c.bg_dark },
    BufferLineModifiedSelected = { fg = c.yellow, bg = c.bg },
    BufferLineModifiedVisible = { fg = c.yellow, bg = c.bg_dark },
    BufferLineDuplicate = { fg = c.fg_gutter, bg = c.bg_dark, italic = true },
    BufferLineDuplicateSelected = { fg = c.fg_secondary, bg = c.bg, italic = true },
    BufferLineDuplicateVisible = { fg = c.comment, bg = c.bg_dark, italic = true },
    BufferLineSeparator = { fg = c.bg_terminal, bg = c.bg_dark },
    BufferLineSeparatorSelected = { fg = c.bg_terminal, bg = c.bg },
    BufferLineSeparatorVisible = { fg = c.bg_terminal, bg = c.bg_dark },
    BufferLineCloseButton = { fg = c.fg_gutter, bg = c.bg_dark },
    BufferLineCloseButtonSelected = { fg = c.comment, bg = c.bg },
    BufferLineCloseButtonVisible = { fg = c.fg_gutter, bg = c.bg_dark },
    BufferLineTab = { fg = c.comment, bg = c.bg_dark },
    BufferLineTabSelected = { fg = c.bg, bg = c.yellow, bold = true },
    BufferLineTabClose = { fg = c.comment, bg = c.bg_dark },
    BufferLineNumbers = { fg = c.fg_gutter, bg = c.bg_dark },
    BufferLineNumbersSelected = { fg = c.yellow, bg = c.bg, bold = true },
    BufferLineNumbersVisible = { fg = c.fg_gutter, bg = c.bg_dark },
    BufferLineOffsetSeparator = { fg = c.bg_highlight, bg = c.bg_sidebar },
    BufferLineDevIconDefault = { fg = c.comment },
    BufferLineDevIconDefaultSelected = { fg = c.fg_secondary },
    BufferLineDevIconDefaultInactive = { fg = c.fg_gutter },
    BufferLineTrunc = { fg = c.comment, bg = c.bg_dark },

    -- ── Breadcrumbs / document symbol nav (navic, dropbar) ──
    NavicText = { fg = c.fg_secondary },
    NavicSeparator = { fg = c.fg_gutter },
    NavicIconsFile = { fg = c.comment },
    NavicIconsModule = { fg = c.cyan },
    NavicIconsNamespace = { fg = c.cyan },
    NavicIconsPackage = { fg = c.cyan },
    NavicIconsClass = { fg = c.yellow },
    NavicIconsMethod = { fg = c.blue },
    NavicIconsProperty = { fg = c.green1 },
    NavicIconsField = { fg = c.green1 },
    NavicIconsConstructor = { fg = c.blue },
    NavicIconsEnum = { fg = c.yellow },
    NavicIconsInterface = { fg = c.yellow },
    NavicIconsFunction = { fg = c.blue },
    NavicIconsVariable = { fg = c.magenta },
    NavicIconsConstant = { fg = c.orange },
    NavicIconsString = { fg = c.green },
    NavicIconsNumber = { fg = c.orange },
    NavicIconsBoolean = { fg = c.orange },
    NavicIconsArray = { fg = c.orange },
    NavicIconsObject = { fg = c.orange },
    NavicIconsKey = { fg = c.purple },
    NavicIconsNull = { fg = c.orange },
    NavicIconsEnumMember = { fg = c.green1 },
    NavicIconsStruct = { fg = c.yellow },
    NavicIconsEvent = { fg = c.yellow },
    NavicIconsOperator = { fg = c.cyan },
    NavicIconsTypeParameter = { fg = c.cyan },
    DropBarMenuNormalFloat = { fg = c.fg, bg = c.bg_float },
    DropBarMenuCurrentContext = { fg = c.yellow, bold = true },
    DropBarIconUISeparator = { fg = c.fg_gutter },
    DropBarIconUIPickPivot = { fg = c.orange },
    DropBarIconUIIndicator = { fg = c.fg_gutter },
    DropBarKindFile = { fg = c.fg_secondary },
    DropBarKindFolder = { fg = c.green },

    -- ── Trouble ─────────────────────────────────────────────
    TroubleText = { fg = c.fg_secondary },
    TroubleCount = { fg = c.magenta, bg = c.surface0 },
    TroubleNormal = { fg = c.fg_secondary, bg = c.bg_sidebar },

    -- ── Flash ───────────────────────────────────────────────
    FlashBackdrop = { fg = c.fg_gutter },
    FlashMatch = { fg = c.bg, bg = c.blue },
    FlashCurrent = { fg = c.bg, bg = c.orange },
    FlashLabel = { fg = c.bg, bg = c.yellow, bold = true },

    -- ── Mini ────────────────────────────────────────────────
    MiniIndentscopeSymbol = { fg = c.dark3 },
    MiniStatuslineModeNormal = { fg = c.bg, bg = c.yellow, bold = true },
    MiniStatuslineModeInsert = { fg = c.bg, bg = c.green, bold = true },
    MiniStatuslineModeVisual = { fg = c.bg, bg = c.magenta, bold = true },
    MiniStatuslineModeReplace = { fg = c.bg, bg = c.red, bold = true },
    MiniStatuslineModeCommand = { fg = c.bg, bg = c.orange, bold = true },
    MiniStatuslineDevinfo = { fg = c.comment, bg = c.bg_dark },
    MiniStatuslineFileinfo = { fg = c.comment, bg = c.bg_dark },
    MiniStatuslineFilename = { fg = c.fg_secondary, bg = c.bg_statusline },
    MiniStatuslineInactive = { fg = c.fg_gutter, bg = c.bg_statusline },
    MiniDiffSignAdd = { fg = c.git_add },
    MiniDiffSignChange = { fg = c.git_change },
    MiniDiffSignDelete = { fg = c.git_delete },
    MiniCursorword = { underline = true },
    MiniCursorwordCurrent = { underline = true },

    -- ── Rainbow delimiters ──────────────────────────────────
    RainbowDelimiterRed = { fg = c.red },
    RainbowDelimiterYellow = { fg = c.yellow },
    RainbowDelimiterBlue = { fg = c.blue },
    RainbowDelimiterOrange = { fg = c.orange },
    RainbowDelimiterGreen = { fg = c.green },
    RainbowDelimiterViolet = { fg = c.purple },
    RainbowDelimiterCyan = { fg = c.cyan },

    -- ── Terminal / health ───────────────────────────────────
    healthError = { fg = c.red },
    healthSuccess = { fg = c.green },
    healthWarning = { fg = c.yellow },
    helpCommand = { fg = c.blue, bg = c.bg_highlight },

    -- ── Terminal ANSI (for :terminal) ───────────────────────
    TermCursor = { fg = c.bg, bg = c.yellow },
  }
end

return M
